### ISSUE TITLE
Picker rotating when host view controller fixed to portrait

### ISSUE THREAD

**Issue by jonathan2708** [skywinder/ActionSheetPicker-3.0#100]
In my app target settings I've ticked all orientations except for 'Upside Down'. In most view controllers I've limited the orientation to 'Portrait' by using the following code :

-(NSUInteger)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}

This locks the view controller to portrait, but the ActionSheetPicker doesn't respect this and animates itself to landscape when the device is rotated. It also has the effect of taking the status bar with it so this ends up displayed along the long edge of the phone.

How should I use the control so that it either locks to portrait, or dismisses when the device is rotated?  I'm building with Xcode 6/iOS 8 SDK.

**Comment by jonathan2708** [comment]
Hi, I'm trying to use this new property by setting it to UIInterfaceOrientationMaskPortrait but I'm still getting the same animation effect when the device is rotated.  Am I doing something wrong?  How can the picker be locked for rotation?  I've updated to version 1.3.10.

**Comment by skywinder** [comment]
@jonathan2708 ok, I reopen issue. I try to fix it soon.
Can you show me example of code, how you init picker and set `supportedInterfaceOrientations` property?

**Comment by jonathan2708** [comment]
Hi, many thanks for looking into this.  I've pasted the code I'm using below 

    ActionSheetDatePicker *datePicker = [[ActionSheetDatePicker alloc] initWithTitle:@"Select Date" datePickerMode:UIDatePickerModeDate selectedDate:defaultDate target:self action:@selector(dateWasSelected:element:) origin:sender];
    [datePicker setSupportedInterfaceOrientations:UIInterfaceOrientationMaskPortrait];
    [datePicker setDoneButton:btnPickerDone];
    [datePicker setCancelButton:btnPickerCancel];
    [datePicker showActionSheetPicker];

**Comment by ralito** [comment]
I am having the exact same problem. The picker is ignoring the value that is set to supportedInterfaceOrientations property.

**Comment by Morpheus2002** [comment]
+1

**Comment by skywinder** [comment]
@ralito , @Morpheus2002 Can't reproduce, thus can't fix it. Can you give me more info, how to reproduce it?

**Comment by Morpheus2002** [comment]
I locked my app to portrait mode with this functions:

```
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation
{
    return UIInterfaceOrientationPortrait;
}

- (NSUInteger)supportedInterfaceOrientations
{
        return UIInterfaceOrientationMaskPortrait;
}


- (BOOL)shouldAutorotate
{
    return NO;   
}
```
As on the screenshot above from @jonathan2708 the app itself stays in portrait mode, but the picker view is rotated and loses background color.

Not using 
```
[datePicker setSupportedInterfaceOrientations:UIInterfaceOrientationMaskPortrait];
```

**Comment by skywinder** [comment]
@jonathan2708 , @ralito , @Morpheus2002  fixed in `1.5.0`

**Comment by gabula80** [comment]
The issue still persists. Scenario to reproduce:

- Lock the interface in UIViewController to Portrait by overriding supportedInterfaceOrientations and returning UIInterfaceOrientationMaskPortrait.

- Set the picker to supportedInterfaceOrientations to Portrait using set setSupportedInterfaceOrientations. Note that it is reproducible with both this property set and not set.

- Leave the phone in portrait and perform the action that opens the picker (like pressing a button).

- Rotate to landscape. The ViewController will not rotate and remain in portrait, but the picker will rotate and mess up its background as shown in the pic from @jonathan2708

**Comment by jonathan2708** [comment]
I agree with @gabula80 - still not fixed in 1.5.0.  As a temporary fix for my portrait-only app I have made the following change to SWActionSheet.m :

    -(NSUInteger)supportedInterfaceOrientations {
        //return UIInterfaceOrientationMaskAll;
        return UIInterfaceOrientationMaskPortrait;
    }

**Comment by skywinder** [comment]
Ok, I reopen this issue.

**Comment by ralito** [comment]
Since my app support all interface orientations for iPad and only Portrait for iPhone as a temporary solution in the SWActionSheet.m I implemented :
 - (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation 
 - (NSUInteger)supportedInterfaceOrientations
I hope this helps someone. :)

**Comment by tbaranes** [comment]
Same issue here. The picker is dismissed well when I'm rotating, but the application is rotating as well. I didn't look too deep, but this looks weir for me in `SWActionSheet`:

```
-(NSUInteger)supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskPortrait;
}
```

That should return the orientation set in the application / AbstractActionSheetPicker to respect the orientation setup, isn't it?

**Comment by skywinder** [comment]
@tbaranes the main point is detect orientation of application. and dismiss picker only when application is `willRotate`. I didn't find clean solution yet.

**Comment by tbaranes** [comment]
Should the picker really be dismissed? I mean, if the orientation isn't available for the device, the picker should just not rotate as the rest of the applicationbut stay open anyway. It should be the developer's choice to dismiss it or not following the case. 

Moreover, that would probably make easier to solve this issue.

**Comment by skywinder** [comment]
@tbaranes I like the way you think. :+1: This behaviour looks logically and clear.

**Comment by pahnev** [comment]
I believe this bug has made it's way back.

**Comment by FedericoHenze** [comment]
This is still happening, how is the appropriate way to avoid the rotation of the picker?

**Comment by jignesh133** [comment]
i am not able to change the cancel and Done buttons colour,and picker text colour.

**Comment by MyNameIsWood** [comment]
@jonathan2708 
paste the following code in SWActionSheetVC/@implementation SWActionSheetVC:
`- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    
    return UIInterfaceOrientationMaskPortrait;
    
}
`
